### ISSUE TITLE
What is license of this?

### ISSUE THREAD

**Issue by KOLANICH** [blowsie/Pure-JavaScript-HTML5-Parser#8]
Is it Apache 2.0, MPL and GNU GPL, [as in original](https://erik.eae.net/simplehtmlparser/simplehtmlparser.js), or or anything else?

**Comment by blowsie** [comment]
I'm no expert on such topics, I would only assume so. Do you have any recommendations for this project?

**Comment by KOLANICH** [comment]
Neither am I. As I understand, the original work was licensed under copyleft licenses, which make all the devaritive works have the same license. Also all they [require you](https://tldrlegal.com/license/mozilla-public-license-1.1-(mpl-1.1)) [to copy](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)) [the notice](https://tldrlegal.com/license/gnu-general-public-license-v2), but you have forked Resig's fork without notice. I think you should
1 copy the notice from the original file to the beginning of your
2 create files with gpl and apache texts and put them to the repo

**Comment by blowsie** [comment]
@KOLANICH Thank you, very useful information.

I did personally mail Resig a few times when starting this fork about licencing but never got a response.
